sudo: false

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer self-update && composer --version
  - composer install

services:
    - mysql
    - mongodb
    - redis-server
    - postgresql

before_script:
  - mysql -u root -e 'create database content;'
  - psql -c 'create database content;' -U postgres

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.0' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    fi

cache:
  directories:
    - vendor
    - $HOME/.composer/cache